<a href="https://colab.research.google.com/github/Thangaraj5591/code/blob/main/excersice_2_sirpi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#  Variables and Data Types
# Write a Python program that swaps two numbers without using a third variable.
a=10
b=20
print("before swapping", a, b)
a=a+b
b=a-b
a=a-b
print("after swapping", a, b)


before swapping 10 20
after swapping 20 10


In [ ]:
# 2. Lists - Nested Lists
# You have a nested list:
# data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
# a) Extract and print the middle element from the nested list.
# b) Flatten the list into a single list [1, 2, 3, 4, 5, 6, 7, 8, 9] without using loops.
data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print("middle element", data[1][1])
single_list = data[0]+data[1]+data[2]
print("flatten single list", single_list)

middle element 5
flatten single list [1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
# 3. Tuples - Tuple Unpacking
# Given:
# values = (100, 200, 300)
# a) Unpack this tuple into three variables and print them.
# b) Swap the values without using a temporary variable.
values = (100, 200, 300)
a,b,c = values
a=a+b+c
b=a-b-c
c=a-b-c
a=a-b-c
print("swapped vaues", a,b,c)

swapped vaues 300 100 200


In [ ]:
# 4. Dictionary - Complex Keys
# Create a dictionary where:
# Keys are tuples representing (x, y) coordinates.
# Values are the sum of x and y.
# Example:
# { (1,2): 3, (3,4): 7, (5,6): 11 }
# Write a function to retrieve the sum for a given coordinate
x= { (1,2): 3, (3,4): 7, (5,6): 11 }
def get_coordinate_sum(coordinates, x):
  if coordinates in x:
    return x[coordinates]
  else:
    return None  # Or raise an exception if appropriate
print(get_coordinate_sum((2,2), x))

None


In [ ]:
# 5. Functions - Nested Functions
# Write a function outer_function(a, b) that:
# Contains an inner function to calculate a² + b².
# Returns the result.
# Call outer_function(3, 4) and print the result.
def ot_function(a,b):
  def in_function(x,y):
     return (x*x)+(y*y)
  return in_function(a,b)
print("nested function", ot_function(3,4))

nested function 25


In [ ]:
# 6. Functions - Lambda & Map
# You are given a list:
# numbers = [1, 2, 3, 4, 5]
# Use a lambda function and map() to generate a list where each number is cubed.
numbers = [1, 2, 3, 4, 5]
print(list(map(lambda n:n*n*n, numbers)))

[1, 8, 27, 64, 125]


In [ ]:
# 7. Functions - Recursion
# Write a recursive function to calculate the sum of digits of a given number.
# Example:
# Input: 1234
# Output: 10  (1+2+3+4)
def rec_fun(n):
  sum= 0
  if (n>0):
    sum=sum+(n%10)
    return sum+rec_fun(n//10)
  else:
    return sum

x=int(input("enter a number:",))
print("sum of digits", rec_fun(x))

enter a number:25
sum of digits 7


In [ ]:
x=int(input("enter a number:",))
sum= 0
while x>0:
  sum=sum+x%10
  x=x//10
print("sum of digits", sum)

enter a number:1234
sum of digits 10


In [ ]:
# 8. List Comprehensions
# Generate a list of all numbers between 1 and 100 that:
# Are divisible by 5
# But not by 3
# Use list comprehension.
li_comp = [i for i in range(1, 101) if i % 5 == 0 and i % 3 != 0]
print(li_comp)

[5, 10, 20, 25, 35, 40, 50, 55, 65, 70, 80, 85, 95, 100]


In [ ]:
# 9. Dictionary - Sorting by Values
# Given:
# scores = {"Alice": 90, "Bob": 85, "Eve": 92}
# Sort this dictionary by values in descending order and print the result.
scores = {"Alice": 90, "Bob": 85, "Eve": 92}
x=sorted(scores.items(), key=lambda item:item[1],reverse=True)
sorted_scores= dict(x)
print(x)

[('Eve', 92), ('Alice', 90), ('Bob', 85)]


In [ ]:
# 10. Sets - Unique Characters
# Write a Python function that takes a string as input and returns:
# A set of unique characters in the string.
# The number of unique characters.
# Example:
# Input: "hello"
# Output: {'h', 'e', 'l', 'o'}, 4

def unique_character(x):
  unique_chars = set(x)
  num_unique_chars = len(unique_chars)
  return unique_chars, num_unique_chars
a = input("Enter a string: ")
print("result:",unique_character(a))


Enter a string: hello
result: ({'l', 'h', 'e', 'o'}, 4)


In [ ]:
# 11. Tuples - Finding Common Elements
# Given two tuples:
# t1 = (1, 2, 3, 4, 5)
# t2 = (4, 5, 6, 7, 8)
#   find and print the common elements.
t1 = (1, 2, 3, 4, 5)
t2 = (4, 5, 6, 7, 8)
set1 = set(t1)
set2 = set(t2)
common_elements=set1.intersection(set2)
common_elements_tuple=tuple(common_elements)
print("The common elements in the given tuples:", common_elements_tuple)

The common elements in the given tuples: (4, 5)


In [ ]:
# 12. Dictionary - Reverse Key-Value Mapping
# Given a dictionary:
# data = {"A": 1, "B": 2, "C": 3}
# Write a program to swap keys and values:
# Output: {1: "A", 2: "B", 3: "C"}
data = {"A": 1, "B": 2, "C": 3}
reversed_data = {value: key for key, value in data.items()}
print(reversed_data)

{1: 'A', 2: 'B', 3: 'C'}


In [ ]:
# 13. Functions - Multiple Return Values
# Write a function that takes two numbers as input and returns:
# Their sum
# Their difference
# Their product
# Their quotient
# Print all four results.
def mu_return(a,b):
  sum = a+b
  diff = a-b
  pro = a*b
  quit = a%b
  return sum, diff,pro, quit

x=int(input("enter number:",))
y=int(input("enter number:",))
print("all results:", mu_return(x,y))

enter number:5
enter number:3
all results: (8, 2, 15, 2)


In [ ]:
# 14.List - Finding Second Largest Number
# Write a function to find the second largest number in a given list without using sort().
# Example:
# Input: [10, 20, 4, 45, 99]
# Output: 45

def sec_largest(L1):
  if len(L1)<2:
    return None
  largest = max(L1)
  L1.remove(largest)
  second_largest = max(L1)
  return second_largest
L = [10, 20, 4, 45, 99]
# second_largest=sec_largest(L)
print("The second largest number is:", sec_largest(L))

The second largest number is: 45


In [ ]:
# 15. List - Pair Sum Problem
# Given a list of numbers and a target sum, find all pairs in the list that add up to the target.
# Example:
# Input: [2, 4, 3, 7, 1, 9], Target: 10
# Output: [(3, 7), (1, 9)]
a=[2, 4, 3, 7, 1, 9]
t=10
out=[]
for i in range(0, len(a)-1):
  for j in range(i+1,len(a)):
    if (a[i]+a[j]==t):
      out.append((a[i],a[j]))
print("the tarket sum 10 :", out)




the tarket sum 10 : [(3, 7), (1, 9)]


In [ ]:
# Pandas & NumPy (5 Questions)
# 16. Pandas - Filtering DataFrame
# You are given the following Pandas DataFrame:
# import pandas as pd
# df = pd.DataFrame({
#     "Name": ["Alice", "Bob", "Charlie", "David"],
#     "Age": [24, 27, 22, 32],
#     "Score": [85, 90, 78, 88]
# })
# Write a one-liner to filter and display only rows where Age is greater than 25.
import pandas as pd
df = pd.DataFrame({
     "Name": ["Alice", "Bob", "Charlie", "David"],
     "Age": [24, 27, 22, 32],
     "Score": [85, 90, 78, 88]
})
print(df[df["Age"]>25])

    Name  Age  Score
1    Bob   27     90
3  David   32     88


In [ ]:
# 17. Pandas - Group By Operation
# You have the following DataFrame:
# df = pd.DataFrame({
#     "Department": ["IT", "HR", "IT", "Finance", "HR"],
#     "Salary": [70000, 50000, 80000, 60000, 52000]
# })
# Write a Pandas command to calculate the average salary per department.
import pandas as pd
df = pd.DataFrame({
     "Department": ["IT", "HR", "IT", "Finance", "HR"],
      "Salary": [70000, 50000, 80000, 60000, 52000]
})
print(df.groupby("Department")["Salary"].mean())


Department
Finance    60000.0
HR         51000.0
IT         75000.0
Name: Salary, dtype: float64


In [ ]:
# 18. NumPy - Create a 5x5 Matrix
# Write a program to create a 5x5 NumPy matrix where:
# The diagonal elements are 1
# All other elements are 0
# Example:
# Output:
# [[1 0 0 0 0]
#  [0 1 0 0 0]
#  [0 0 1 0 0]
#  [0 0 0 1 0]
#  [0 0 0 0 1]]
# #
import numpy as np
matrix = np.zeros((5, 5), dtype=int)
np.fill_diagonal(matrix, 1)
print(matrix)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [ ]:
# 19. NumPy - Element-wise Operations
# Given two NumPy arrays:
# import numpy as np
# a = np.array([1, 2, 3, 4])
# b = np.array([10, 20, 30, 40])
# Perform element-wise:
# Addition
# Multiplication
# Power (a^b)
# # Print the results.
import numpy as np
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])
print("addition", a+b)
print("multiplication", a*b)
print("power", a**b)

addition [11 22 33 44]
multiplication [ 10  40  90 160]
power [              1         1048576 205891132094649               0]


In [ ]:
# 20. NumPy - Find Index of Maximum Value
# Given:
# arr = np.array([10, 25, 39, 50, 19])
# Write a one-liner to find the index of the maximum value.


50


In [ ]:
import numpy as np
arr = np.array([10, 25, 39, 50, 19])
print(arr.max())

50
